### PR TITLE
Updates for easy pip installation

### PR DESCRIPTION
**Pull request by rmjarvis**
This PR includes some minor changes to setup.py and other files to make it easier to get treegp pip installable.

There is a checklist called release.txt, which goes through the steps you need to do when releasing a new version.  It's not too complicated, but I always forget bits here and there, so I have a version of this in all my repos.  :)  

I went ahead and followed this script to release version 0.1.0 on pip with the current version of the code, but Pierre-François, I was thinking that it would be good to have you try to follow the procedure to also release this as either 0.2.0 or 0.1.1, or even 1.0.0 if you feel ready to call it that.  Basically just make sure that you understand all the steps, so you can do it yourself in the future as appropriate.

### CODE REVIEW

**Comment by PFLeget** [comment]
Thank you a lot, for all of this Mike! I guess the version 1.0.0 will come soon as the paper of the astrometry of HSC should come out soon.

**Comment by rmjarvis** [comment]
I'd recommend trying to follow the procedure yourself to release the current master as v0.2.0 now.  For one, there were a couple minor adjustments (most importantly the iminuit version for py2.7) since what I released as v0.1.0.  But more importantly, we should make sure you understand all the steps, so you'll have some confidence that you know what to do when you're ready to release 1.0.0.

**Comment by PFLeget** [comment]
I'll do that right now like that I'll see if I have a problem to get the v0.2.0 pip installable

**Comment by PFLeget** [comment]
I am at the last step for releasing the version `0.2.0` of `treegp` (`twine upload dist/treegp-0.2.0.tar.gz`). I am not allowed to push a new version because I am not the owner of the Pypi version. I just created an account under Pypi (PFLeget). Is it you @rmjarvis  that should allow me to push? 
Thanks in advance!

**Comment by rmjarvis** [comment]
Good.  OK.  I think I added you as an owner to treegp on pypi now.  cf. https://pypi.org/manage/project/treegp/collaboration/
So try again to see if it works.

**Comment by PFLeget** [comment]
It looks like it is working :)! Than you so much!

**Comment by rmjarvis** [comment]
Great!

**Pull request merged**
